server:
  port: 7777
  servlet:
    context-path: /metastore

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/metastore?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
